name: caimel-stack
services:
  boilerplate:
    build:
      dockerfile: apps/boilerplate/docker/dockerfile
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "127.0.0.1:3044:3000"
    working_dir: /nextjs
    environment:
      APP_NAME: "boilerplate"
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "200"
      NEXT_TELEMETRY_DISABLED: "1"
      CI: "true"
      PNPM_STORE_DIR: /home/node/.pnpm-store
      ADMIN_USERNAME: ${RANDOM_USERNAME}
      ADMIN_PASSWORD: ${STRONG_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    volumes:
      - ./:/nextjs:rw
      - volume_nextjs_pnpm_store:/home/node/.pnpm-store:rw
    command: ["pnpm", "turbo", "run", "dev", "--filter=boilerplate"]
    networks:
      - proxy
      - caimel-stack

    healthcheck:
      test: ["CMD", "true"]

networks:
  proxy:
    external: true
  caimel-stack:
    external: true

volumes:
  volume_nextjs_pnpm_store:
