name: caimel-stack
services:
  boilerplate:
    build:
      dockerfile: apps/boilerplate/docker/dockerfile
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "127.0.0.1:3044:3000"
    working_dir: /nextjs
    environment:
      APP_NAME: "boilerplate"
      PNPM_STORE_DIR: /home/node/.pnpm-store
      TURBO_TELEMETRY_DISABLED: "1"
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "200"

      CI: "true"
      ADMIN_USERNAME: ${RANDOM_USERNAME}
      ADMIN_PASSWORD: ${STRONG_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    volumes:
      - ./:/nextjs:rw
      - volume_boilerplate_pnpm_store:/home/node/.pnpm-store:rw
    command:
      [
        "bash",
        "-c",
        "cd /nextjs && pnpm install --no-frozen-lockfile && pnpm turbo run dev --filter=boilerplate",
      ]
    networks:
      - proxy
      - caimel-stack
    healthcheck:
      test: ["CMD", "true"]

  boilerplate2:
    build:
      dockerfile: apps/boilerplate2/docker/dockerfile
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "127.0.0.1:3045:3000"
    working_dir: /nextjs
    environment:
      APP_NAME: "boilerplate2"
      PNPM_STORE_DIR: /home/node/.pnpm-store
      TURBO_TELEMETRY_DISABLED: "1"
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "200"

      CI: "true"
      ADMIN_USERNAME: ${RANDOM_USERNAME}
      ADMIN_PASSWORD: ${STRONG_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    volumes:
      - ./:/nextjs:rw
      - volume_boilerplate2_pnpm_store:/home/node/.pnpm-store:rw
    command:
      [
        "bash",
        "-c",
        "cd /nextjs && pnpm install --no-frozen-lockfile && pnpm turbo run dev --filter=boilerplate2",
      ]
    networks:
      - proxy
      - caimel-stack
    healthcheck:
      test: ["CMD", "true"]

networks:
  proxy:
    external: true
  caimel-stack:
    external: true

volumes:
  volume_boilerplate_pnpm_store:
  volume_boilerplate2_pnpm_store:
